### ISSUE TITLE
action

### ISSUE THREAD

**Issue by benjaminkosolov** [benjaminkosolov/Morpheus#2]
could you confirm me the action of the code?

**Comment by felipricardo** [comment]
The program reads each file in the specified directory, except for files with the ".exe" extension, encrypts it using the key "R?\n??i??" and saves the encrypted file with the ".axx" extension. Then, the program deletes the original file and pauses for a specified amount of time in milliseconds before proceeding to the next file.

The `EncryptDir` function is responsible for getting all the files in the specified directory and calling the `EncryptFile` function to encrypt each of them. The `EncryptFile` function uses the specified key to set up the DES algorithm and encrypts the input file, writing the result to the output file.
